project:
  type: website
  execute-dir: project
  resources: [
   scripts,
   dataset_for_shiny
  ]

website:
  title: "MA [46]15 Final Project TEAM 9"
  navbar:
    right:
      - text: About
        file: about.qmd
      - text: Big Picture
        file: big_picture.qmd
      - text: Analysis
        file: analysis.qmd
      - text: Data
        file: data.qmd

format:
  html:
    theme: cosmo
    css: styles.css



