<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Here we provide a detailed analysis using more sophisticated statistics techniques.">

<title>MA [46]15 Final Project TEAM 9 - Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA [46]15 Final Project TEAM 9</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html" rel="" target="">
 <span class="menu-text">Big Picture</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" rel="" target="" aria-current="page">
 <span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivation-for-data-analysis" id="toc-motivation-for-data-analysis" class="nav-link active" data-scroll-target="#motivation-for-data-analysis">Motivation for Data Analysis</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  <li><a href="#exploration" id="toc-exploration" class="nav-link" data-scroll-target="#exploration">Exploration</a></li>
  <li><a href="#national-level-view" id="toc-national-level-view" class="nav-link" data-scroll-target="#national-level-view">National-Level View</a></li>
  <li><a href="#relationship-between-school-support-and-harassment-reports" id="toc-relationship-between-school-support-and-harassment-reports" class="nav-link" data-scroll-target="#relationship-between-school-support-and-harassment-reports">Relationship between School Support and Harassment Reports</a>
  <ul class="collapse">
  <li><a href="#how-school-support-and-student-race-predict-harassment-allegation-rates" id="toc-how-school-support-and-student-race-predict-harassment-allegation-rates" class="nav-link" data-scroll-target="#how-school-support-and-student-race-predict-harassment-allegation-rates">How School Support and Student Race Predict Harassment Allegation Rates</a></li>
  <li><a href="#trends-and-correlations" id="toc-trends-and-correlations" class="nav-link" data-scroll-target="#trends-and-correlations">Trends and Correlations</a></li>
  <li><a href="#massachusetts-focus" id="toc-massachusetts-focus" class="nav-link" data-scroll-target="#massachusetts-focus">Massachusetts Focus</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#challenges-and-limitations" id="toc-challenges-and-limitations" class="nav-link" data-scroll-target="#challenges-and-limitations">Challenges and Limitations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    Here we provide a detailed analysis using more sophisticated statistics techniques.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><img src="images/cover_pic.png" class="img-fluid"></p>
<section id="motivation-for-data-analysis" class="level1">
<h1>Motivation for Data Analysis</h1>
<p>Our project aims to understand the complex factors influencing harassment, and bullying incidents across public schools in the United States. We start off our analysis on a high-level view of harassment and bullying nationally, but end up particularly focusing on how school-level resources (counselors, psychologists, security staff), student demographics, and geographic location contribute to reported incidents.</p>
<p>Given persistent racial, disability-related, and orientation-based disparities, our goal is to identify actionable patterns that can inform equity-focused educational reforms.</p>
</section>
<section id="research-questions" class="level1">
<h1>Research Questions</h1>
<ul>
<li>Do schools with more support staff report fewer harassment incidents?</li>
<li>How does harassment rate vary across different identity categories (e.g., race, disability, religion, sexual orientation)?</li>
<li>Are geographic patterns evident - do some states or regions report higher normalized rates?</li>
</ul>
</section>
<section id="exploration" class="level1">
<h1>Exploration</h1>
<p>One of the most pressing concerns that led us to analyze this data was to understand the groups (based on race, disability, religion, sexual orientation, etc.) that were most affected nationwide.</p>
</section>
<section id="national-level-view" class="level1">
<h1>National-Level View</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sex_orientation.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Normalized rate of harassment allegations based on sexual orientation across U.S. states</figcaption>
</figure>
</div>
<p>This map shows the normalized rate of allegations based on sexual orientation. Massachusetts, New York, and New Jersey all had high rates with closer to 10%. The northwest region showed very few or no reported cases.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/religion.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Normalized rate of harassment allegations based on religion across U.S. states</figcaption>
</figure>
</div>
<p>This map highlights religion-based harassment allegations. While overall rates were lower compared to other categories, Massachusetts again stands out. States like Utah and Idaho had zero or near-zero cases.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/race.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Normalized rate of harassment allegations based on race across U.S. states</figcaption>
</figure>
</div>
<p>This map displays allegations of harassment due to race, color, or national origin. Massachusetts once again leads with the highest number of allegations, followed closely by New York and California. The southeast and parts of the northwest had lower reported rates. However, these graphs fail to provide an accurate representation of the number of allegations within each of these categories (race, religion, sex) as this is only depicting the reported incidents. Unreported incidents likely in the northwestern states are not depicted in the data itself so we fail to make appropriate inferences and comparisons between the states themselves.</p>
</section>
<section id="relationship-between-school-support-and-harassment-reports" class="level1">
<h1>Relationship between School Support and Harassment Reports</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>Slope (β1): β1=−0.352, it indicates that a 1% increase in total support staff is associated with a 0.352% decrease in harassment allegations per 100 students. This negative elasticity suggests that more support staff correlates with fewer reported incidents.</p></li>
<li><p>Intercept (β0): This represents the expected log of allegations per 100 students when the log of total support staff is zero.</p></li>
<li><p>R^2 = 0.08 : This means that approximately 8% of the variability in harassment allegations per 100 students is explained by the model. While the relationship is statistically significant, other factors not included in the model likely influence the number of allegations.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Model Fit Statistics Table</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">R-squared</td>
<td style="text-align: right;">0.0804672</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adjusted R-squared</td>
<td style="text-align: right;">0.0804210</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sigma</td>
<td style="text-align: right;">1.0540021</td>
</tr>
<tr class="even">
<td style="text-align: left;">F-statistic</td>
<td style="text-align: right;">1742.0380402</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p-value</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Degrees of Freedom</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The linear regression model reveals a statistically significant relationship between log total school support staff and log harassment allegations per 100 students. With an R-squared of 0.0805, the model explains approximately 8% of the variation in the outcome, suggesting a modest explanatory power. The adjusted R-squared is nearly identical, indicating that the model is not overfitting despite its simplicity. The F-statistic is high (1742.04) with a p-value effectively zero, confirming that the predictor contributes meaningfully to explaining variation in the response variable. The residual standard error (sigma) is about 1.05 on the log scale, indicating the typical prediction error. Overall, while the model is statistically strong, its predictive power is limited, highlighting the need for additional explanatory variables to better understand harassment reports in schools.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Our model residuals are mostly normal, especially in the center, which is reassuring for coefficient inference. But the tail deviations suggest the presence of outliers or non-normality in extreme values. Thus, Inferences involving prediction intervals or extreme outcomes may be less reliable. Therefore, though the model appears reasonable in form, but the presence of heteroskedasticity suggests we might consider using robust standard errors when reporting p-values and confidence intervals.</p>
<section id="how-school-support-and-student-race-predict-harassment-allegation-rates" class="level2">
<h2 class="anchored" data-anchor-id="how-school-support-and-student-race-predict-harassment-allegation-rates">How School Support and Student Race Predict Harassment Allegation Rates</h2>
<p><img src="images/Allegation.PNG" class="img-fluid"></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    1.16     0.0905     12.9  1.50e- 37
2 log_support   -0.369    0.0121    -30.6  2.48e-197
3 RaceAS        -0.159    0.0983     -1.62 1.06e-  1
4 RaceBL         0.153    0.0924      1.65 9.82e-  2
5 RaceHI        -0.801    0.0930     -8.61 8.27e- 18
6 RaceHP         0.885    0.216       4.11 4.01e-  5
7 RaceTR         0.415    0.0951      4.36 1.32e-  5
8 RaceWH        -1.45     0.0928    -15.6  2.06e- 54</code></pre>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="trends-and-correlations" class="level2">
<h2 class="anchored" data-anchor-id="trends-and-correlations">Trends and Correlations</h2>
<ul>
<li>AM (Red): Shows a weak and slightly negative correlation between school support and harassment rates. Increased support does not significantly change allegations among American Indian/Alaska Native students.</li>
<li>AS (Brown): Displays a slight negative correlation. Allegation rates decrease with more support, though the relationship is not statistically strong.</li>
<li>BL (Green): Shows a modest downward trend, suggesting that increased support staff may be linked to lower harassment allegations among Black students, though with considerable variability.</li>
<li>HI (Teal): Exhibits a clearer negative correlation. Schools with higher support tend to report fewer harassment cases involving Hispanic students.</li>
<li>HP (Light Blue): Shows a near-flat to slightly positive slope. This group reports higher baseline harassment rates, and increased support staff does not appear to lower the rate significantly.</li>
<li>TR (Purple): Displays a moderately negative trend, implying a potential benefit of school support staff in reducing harassment against multiracial students.</li>
<li>WH (Pink): Has one of the steepest negative slopes. Greater support staff presence is strongly associated with fewer allegations among White students.</li>
</ul>
<p>Across racial groups, schools with greater staff support — including counselors, psychologists, and security, tend to report fewer race-based harassment allegations per 100 students. This trend suggests that investments in support personnel may contribute to safer, more inclusive school environments, particularly for groups like White, Hispanic, and Multiracial students. However, the impact is not uniform, and further investigation may be needed for groups such as Native Hawaiian/Pacific Islanders, who experience high baseline rates and limited benefit from staffing increases.</p>
</section>
<section id="massachusetts-focus" class="level2">
<h2 class="anchored" data-anchor-id="massachusetts-focus">Massachusetts Focus</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 98010 Columns: 395
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (5): LEA_STATE, LEA_STATE_NAME, LEA_NAME, NAME, JJ
dbl (390): LEAID, SCHID, COMBOKEY, HBALLEGATIONS_SEX, HBALLEGATIONS_ORI, HBA...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep =
"~~~")), : Ignoring unknown parameters: `label.x.npc` and `label.y.npc`</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..eq.label..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(eq.label)` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Regardless of the missing data across multiple states, we noticed that Massachusetts had a lot of data, and also had the highest proportion of allegations compared to all states. Therefore, from these observations, we narrowed our focus down to the state of Massachusetts, and identified key trends in relation to school support resources (counselors, psychologists, security), and demographics.</p>
<p>This log-log regression focuses on schools in Massachusetts and shows a modest negative association between school support staffing and harassment allegations per 100 students. The downward slope (𝑦 = −0.376 − 0.325𝑥, 𝑅² = 0.08) suggests that schools with more counselors, psychologists, and security staff tend to report fewer harassment incidents, though the relationship is relatively weak. Still, the trend aligns with our broader hypothesis that greater support infrastructure may help create safer school environments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load school support data</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>support <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"dataset/School Support.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 98010 Columns: 19
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (8): LEA_STATE, LEA_STATE_NAME, LEAID, LEA_NAME, SCHID, SCH_NAME, COMBO...
dbl (11): SCH_FTESECURITY_LEO, SCH_FTESECURITY_GUA, SCH_FTETEACH_TOT, SCH_FT...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for Massachusetts and compute total support</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>support_ma <span class="ot">&lt;-</span> support <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(LEA_STATE <span class="sc">==</span> <span class="st">"MA"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">TOTAL_SUPPORT =</span> <span class="fu">as.numeric</span>(SCH_FTECOUNSELORS) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.numeric</span>(SCH_FTESERVICES_PSY) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.numeric</span>(SCH_FTESECURITY_GUA)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(TOTAL_SUPPORT))  <span class="co"># Remove missing values</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># View summary of support levels</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(support_ma<span class="sc">$</span>TOTAL_SUPPORT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -9.000   1.167   2.100   3.267   4.000  37.360 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: Top 10 schools by support staff</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>support_ma <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SCH_NAME, TOTAL_SUPPORT) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(TOTAL_SUPPORT)) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   SCH_NAME                                TOTAL_SUPPORT
   &lt;chr&gt;                                           &lt;dbl&gt;
 1 Newbury Elementary                               37.4
 2 B M C Durfee High                                33.8
 3 Weymouth High School                             32.7
 4 Gr Lowell Regional Vocational Technical          30  
 5 Brockton High                                    29.8
 6 Cambridge Rindge and Latin                       29.4
 7 Lawrence High School                             25.8
 8 New Bedford High                                 25.8
 9 Lowell High                                      25.2
10 Taunton High                                     21.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load datasets</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>support <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"dataset/School Support.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 98010 Columns: 19
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (8): LEA_STATE, LEA_STATE_NAME, LEAID, LEA_NAME, SCHID, SCH_NAME, COMBO...
dbl (11): SCH_FTESECURITY_LEO, SCH_FTESECURITY_GUA, SCH_FTETEACH_TOT, SCH_FT...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>enrollment <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"dataset/Enrollment.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 98010 Columns: 233
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (8): LEA_STATE, LEA_STATE_NAME, LEAID, LEA_NAME, SCHID, SCH_NAME, COMB...
dbl (225): SCH_ENR_HI_M, SCH_ENR_HI_F, SCH_ENR_HI_X, SCH_ENR_AM_M, SCH_ENR_A...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for Massachusetts only</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>support_ma <span class="ot">&lt;-</span> support <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LEA_STATE <span class="sc">==</span> <span class="st">"MA"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>enrollment_ma <span class="ot">&lt;-</span> enrollment <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LEA_STATE <span class="sc">==</span> <span class="st">"MA"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate total support staff</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>support_ma <span class="ot">&lt;-</span> support_ma <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Total_Support =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">starts_with</span>(<span class="st">"SCH_FTE"</span>)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SCHID, SCH_NAME, Total_Support)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Get bottom 5 schools with lowest support staff</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>bottom5 <span class="ot">&lt;-</span> support_ma <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Total_Support) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter enrollment for bottom 5 schools</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>enrollment_bottom5 <span class="ot">&lt;-</span> enrollment_ma <span class="sc">%&gt;%</span> <span class="fu">filter</span>(SCHID <span class="sc">%in%</span> bottom5<span class="sc">$</span>SCHID)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate racial breakdown with safe sums</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>race_table_bottom <span class="ot">&lt;-</span> enrollment_bottom5 <span class="sc">%&gt;%</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Enrollment =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., TOT_ENR_M, TOT_ENR_F, TOT_ENR_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Asian =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_AS_M, SCH_ENR_AS_F, SCH_ENR_AS_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Black =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_BL_M, SCH_ENR_BL_F, SCH_ENR_BL_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hispanic =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_HI_M, SCH_ENR_HI_F, SCH_ENR_HI_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">White =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_WH_M, SCH_ENR_WH_F, SCH_ENR_WH_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">Other =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_AM_M, SCH_ENR_AM_F, SCH_ENR_AM_X,</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>                                SCH_ENR_HP_M, SCH_ENR_HP_F, SCH_ENR_HP_X,</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>                                SCH_ENR_TR_M, SCH_ENR_TR_F, SCH_ENR_TR_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>)</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">Asian =</span> <span class="fu">round</span>(Asian <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">Black =</span> <span class="fu">round</span>(Black <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hispanic =</span> <span class="fu">round</span>(Hispanic <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">White =</span> <span class="fu">round</span>(White <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">Other =</span> <span class="fu">round</span>(Other <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SCH_NAME, Asian, Black, Hispanic, White, Other) <span class="sc">%&gt;%</span></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">match</span>(SCH_NAME, bottom5<span class="sc">$</span>SCH_NAME))  <span class="co"># Match order</span></span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the table</span></span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(race_table_bottom)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   SCH_NAME                                Asian Black Hispanic White Other
   &lt;chr&gt;                                   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 Worcester Secure Treatment                0     0        0     0       0
 2 Commonwealth Secure Detention             0     0        0     0       0
 3 Sharp Transistion Revocation Unit         0     0        0     0       0
 4 Butler Center                             0     0        0     0       0
 5 Brockton Revocation                       0     0        0     0       0
 6 Roxbury Prep High School - Upper Campus   0    62.2     30.1   0       0
 7 Roxbury Prep Dorchester Campus            0    49.1     45.9   0       0
 8 Kennedy Academy for Health Careers        0    35.1     54.3   2.1     0
 9 UP Academy Boston                         2.3  42.1     44     1       0
10 The B.R.I.D.G.E. Program                  0     0       46.7   6.7     0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 1: Filter out rows with all race counts == 0</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>race_table_bottom_clean <span class="ot">&lt;-</span> race_table_bottom <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Asian <span class="sc">+</span> Black <span class="sc">+</span> Hispanic <span class="sc">+</span> White <span class="sc">+</span> Other <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 2: Convert to long format for plotting</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>race_long_bottom <span class="ot">&lt;-</span> race_table_bottom_clean <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> Asian<span class="sc">:</span>Other, <span class="at">names_to =</span> <span class="st">"Race"</span>, <span class="at">values_to =</span> <span class="st">"Percent"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>race_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Asian"</span> <span class="ot">=</span> <span class="st">"#66c2a5"</span>,     </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Black"</span> <span class="ot">=</span> <span class="st">"#fc8d62"</span>,     </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hispanic"</span> <span class="ot">=</span> <span class="st">"#8da0cb"</span>, </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span> <span class="ot">=</span> <span class="st">"#a6d854"</span>,     </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"White"</span> <span class="ot">=</span> <span class="st">"#e78ac3"</span>     </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co"># === Step 3: Plot</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(race_long_bottom, <span class="fu">aes</span>(<span class="at">x =</span> SCH_NAME, <span class="at">y =</span> Percent, <span class="at">fill =</span> Race)) <span class="sc">+</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Racial Demographics of MA Schools with Top 5 Lowest School Support Staff"</span>,</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"School Name"</span>,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percent of Total Enrollment"</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> race_colors) <span class="sc">+</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">30</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load datasets</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>support <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"dataset/School Support.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 98010 Columns: 19
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (8): LEA_STATE, LEA_STATE_NAME, LEAID, LEA_NAME, SCHID, SCH_NAME, COMBO...
dbl (11): SCH_FTESECURITY_LEO, SCH_FTESECURITY_GUA, SCH_FTETEACH_TOT, SCH_FT...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>enrollment <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"dataset/Enrollment.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 98010 Columns: 233
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (8): LEA_STATE, LEA_STATE_NAME, LEAID, LEA_NAME, SCHID, SCH_NAME, COMB...
dbl (225): SCH_ENR_HI_M, SCH_ENR_HI_F, SCH_ENR_HI_X, SCH_ENR_AM_M, SCH_ENR_A...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for Massachusetts</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>support_ma <span class="ot">&lt;-</span> support <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LEA_STATE <span class="sc">==</span> <span class="st">"MA"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>enrollment_ma <span class="ot">&lt;-</span> enrollment <span class="sc">%&gt;%</span> <span class="fu">filter</span>(LEA_STATE <span class="sc">==</span> <span class="st">"MA"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate total support staff per school</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>support_ma <span class="ot">&lt;-</span> support_ma <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Total_Support =</span> <span class="fu">rowSums</span>(<span class="fu">select</span>(., <span class="fu">starts_with</span>(<span class="st">"SCH_FTE"</span>)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SCHID, SCH_NAME, Total_Support)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Get top 5 schools with highest support staff</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>top5 <span class="ot">&lt;-</span> support_ma <span class="sc">%&gt;%</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_Support)) <span class="sc">%&gt;%</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">5</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter enrollment for those schools</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>enrollment_top5 <span class="ot">&lt;-</span> enrollment_ma <span class="sc">%&gt;%</span> <span class="fu">filter</span>(SCHID <span class="sc">%in%</span> top5<span class="sc">$</span>SCHID)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean and calculate race counts and percentages</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>race_table <span class="ot">&lt;-</span> enrollment_top5 <span class="sc">%&gt;%</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Total_Enrollment =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., TOT_ENR_M, TOT_ENR_F, TOT_ENR_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Asian =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_AS_M, SCH_ENR_AS_F, SCH_ENR_AS_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Black =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_BL_M, SCH_ENR_BL_F, SCH_ENR_BL_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hispanic =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_HI_M, SCH_ENR_HI_F, SCH_ENR_HI_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">White =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_WH_M, SCH_ENR_WH_F, SCH_ENR_WH_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>),</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">Other =</span> <span class="fu">pmax</span>(<span class="fu">rowSums</span>(<span class="fu">select</span>(., SCH_ENR_AM_M, SCH_ENR_AM_F, SCH_ENR_AM_X,</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>                                SCH_ENR_HP_M, SCH_ENR_HP_F, SCH_ENR_HP_X,</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>                                SCH_ENR_TR_M, SCH_ENR_TR_F, SCH_ENR_TR_X), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">0</span>)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">Asian =</span> <span class="fu">round</span>(Asian <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">Black =</span> <span class="fu">round</span>(Black <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">Hispanic =</span> <span class="fu">round</span>(Hispanic <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">White =</span> <span class="fu">round</span>(White <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">Other =</span> <span class="fu">round</span>(Other <span class="sc">/</span> Total_Enrollment <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SCH_NAME, Asian, Black, Hispanic, White, Other) <span class="sc">%&gt;%</span></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">match</span>(SCH_NAME, top5<span class="sc">$</span>SCH_NAME))  <span class="co"># Match order</span></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Print final racial breakdown table</span></span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(race_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  SCH_NAME                                Asian Black Hispanic White Other
  &lt;chr&gt;                                   &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Brockton High                             2.4  62       17    14.2   4.5
2 Lawrence High School                      2.9   0       92.1   0     0  
3 Cambridge Rindge and Latin               10.3  27.3     15.2  37.2  10  
4 Lowell High                              29.6  11       35.1  20.8   3.9
5 Gr Lowell Regional Vocational Technical  17.4   5.7     36.7  36.8   3.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape data to long format for ggplot</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>race_long <span class="ot">&lt;-</span> race_table <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> Asian<span class="sc">:</span>Other, <span class="at">names_to =</span> <span class="st">"Race"</span>, <span class="at">values_to =</span> <span class="st">"Percent"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot stacked bar chart</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(race_long, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(SCH_NAME, <span class="sc">-</span>Percent), <span class="at">y =</span> Percent, <span class="at">fill =</span> Race)) <span class="sc">+</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Racial Demographics of MA Schools with Top 5 Highest School Support Staff"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"School Name"</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percentage of Enrollment"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Race"</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> race_colors)<span class="sc">+</span> </span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The first graph shows that schools in Massachusetts with the lowest levels of school support staff tend to serve predominantly Black and Hispanic student populations, with very low proportions of White or Asian students. In contrast, the second graph reveals that schools with the highest levels of support staff exhibit more racial diversity, with some having a significantly higher proportion of White and Asian students. This contrast suggests a potential equity gap, where schools serving more students of color have less access to support resources.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Our analysis finds that schools with more support staff (counselors, psychologists, and security) tend to report slightly fewer harassment incidents, particularly in Massachusetts, although the effect is modest. Racial disparities are also evident: schools with high proportions of non-White students often have fewer support resources, raising equity concerns. While increased staffing is weakly correlated with improved outcomes, this analysis highlights the importance of targeted, equity-focused interventions to address harassment and disciplinary disparities across student demographics.</p>
</section>
<section id="challenges-and-limitations" class="level1">
<h1>Challenges and Limitations</h1>
<p>One key limitation is the underreporting of incidents, particularly in states with low reported rates (e.g., northwestern states), which may skew comparisons. Additionally, the data only reflects documented cases, leaving gaps in understanding the full scope of harassment and bullying. Another challenge is the lack of granularity in school-level resource allocation, making it difficult to directly correlate support staff presence with incident rates. Finally, demographic disparities in reporting (e.g., male vs.&nbsp;female reports) may introduce bias in interpreting which groups are most affected.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>